### PR TITLE
Use kerberos support directly from python-jenkins

### PR DESCRIPTION
**Pull request by hrubi**
Reverts gooddata/jenkins-job-builder#6

Patch in python-jenkins is released https://pypi.python.org/pypi/python-jenkins/0.4.13
https://git.openstack.org/cgit/openstack/python-jenkins/log/?h=0.4.13
https://git.openstack.org/cgit/openstack/python-jenkins/commit/?h=0.4.13&id=d2cfca68d03e0ab5723f17750b2dfe517d0cf06f

### CODE REVIEW

**Comment by ghost** [comment]
let's also update python-jenkins minimal version to 0.4.13 in requirements.txt to avoid a possible regression

**Comment by ghost** [comment]
@michalvanco tested. please merge

EDIT: actually hold on, I think we should revert one more commit

**Comment by michalvanco** [comment]
so, ready or not yet? :)

**Comment by ghost** [comment]
not yet, sry

**Comment by hrubi** [comment]
Depends on https://github.com/gooddata/ci-infra/pull/1720

**Comment by ghost** [comment]
https://github.com/gooddata/ci-infra/pull/1720 merged

@michalvanco please merge now :)

**Pull request merged**
