### PR TITLE
SETI-6637: Add support for warning-ng plugin with checkstyle tool

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by r0039** [comment]
LGTM

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/jenkins-job-builder-fossa-scanning-oss-zuul-el7/3/ : SUCCESS in 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/jenkins-job-builder-merge-compliance-check/2/ : SUCCESS in 22s

**Pull request merged**
